### ISSUE TITLE
Modal UI > Labels

### ISSUE THREAD

**Issue by mfendeksilverstripe** [maxime-rainville/silverstripe-anyfield#30]
# Modal UI > Labels

Some of the labels are hard coded, we need to change these to pull dynamic values.

## New model state

This is when user clicks on "add new" button (creating new model).

![Screenshot 2023-12-13 at 9 40 38 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/4710e5fc-0788-4dc2-bd0e-03d2a302285c)

* A - the label should be showing New {model name}
* B - the label should be showing Create

The general aim is to make the UI labels consistent with `GridField`, see examples below.

![Screenshot 2023-12-13 at 9 53 21 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/55c3db81-6518-4f0a-8621-74bdf8904575)

![Screenshot 2023-12-13 at 9 53 30 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/26345883-00b5-4b0e-900e-940c449fb294)

## Existing model state

This is when user clicks on one of the existing models (edit existing model).

![Screenshot 2023-12-13 at 9 40 47 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/70e61768-dc34-4a8a-a4c5-08c60fed4aa3)

* A - the label should be showing Edit {model name}
* B - the label should be showing Save

The general aim is to make the UI labels consistent with `GridField`, see example below.

![Screenshot 2023-12-13 at 9 55 16 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/a2e1fc66-6723-4d98-97de-8d5c2fd79072)

**Comment by maxime-rainville** [comment]
I'm pretty confident this would be a trivial fix.

**Comment by mfendeksilverstripe** [comment]
Fixes applied in

https://github.com/maxime-rainville/silverstripe-anyfield/pull/35
https://github.com/maxime-rainville/silverstripe-anyfield/pull/37
