### ISSUE TITLE
Issues with File Upload and Saving in AnyField with Link::class Relation

### ISSUE THREAD

**Issue by moritz-sauer-13** [maxime-rainville/silverstripe-anyfield#32]
**Description:**
I am experiencing difficulties with uploading and saving files using the AnyField configured for a relation with Link::class. When attempting to upload a file through this field, I consistently receive the error message: "key for class 'SilverStripe\AnyField\Extensions\ModalController' is required". Additionally, when I select a file from existing files and then close the modal or save the overarching DataObject, the file fails to be saved. This issue persistently prevents the proper use of this feature.

**Question:**
Is this behavior indicative of a bug in the module, or could it be a result of some oversight in my configuration? Do you need further information in reproducing this? 

Here is a part of my current code: 

```
class HeroSlide extends DataObject
{

    private static $db = [
        'SortOrder' => 'Int',
        'Title' => 'Text',
    ];

    private static $has_one = [
        'PrimaryButton' => Link::class,
        'SecondaryButton' => Link::class,
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->removeByName([
            'PrimaryButtonID',
            'SecondaryButtonID',
        ]);
        $fields->addFieldsToTab('Root.Main', [
            TextField::create('Title', 'Titel'),
            AnyField::create('PrimaryButton', 'Primärer Button'),
            AnyField::create('SecondaryButton', 'Sekundärer Button')
        ]);

        return $fields;
    }
}

```

**Comment by maxime-rainville** [comment]
Pretty sure that's a bug with `AnyField`. I suspected this scenario would fall flat on its face.

If the object you want to manage with `AnyField` has an `UploadField` it will likely not work.

I'll try to have a glance, but it will likely not be this week.

**Comment by maxime-rainville** [comment]
Got a PR which I think addresses the problem. Still needs to look at the CI.

https://github.com/maxime-rainville/silverstripe-anyfield/pull/35

**Comment by mfendeksilverstripe** [comment]
Related PR merged
